# golangci-lint configuration for AIED

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - third_party
    - testdata

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unparam
    - gocritic
    - gocyclo
    - godot
    - gosec
    - bodyclose
    - stylecheck
    - revive
    
  disable:
    - gomnd
    - lll
    - gochecknoglobals
    - funlen
    - wsl

linters-settings:
  gofmt:
    simplify: true
    
  goimports:
    local-prefixes: github.com/dshills/aied
    
  govet:
    check-shadowing: true
    
  gocyclo:
    min-complexity: 15
    
  gosec:
    excludes:
      - G104  # Unhandled errors in defer
      
issues:
  max-issues-per-linter: 50
  max-same-issues: 10
  
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
EOF < /dev/null